// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: querystring.proto

package com.auzmor.protobuf;

public final class QueryProtoBuf {
  private QueryProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryStringOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QueryString)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string var1 = 1;</code>
     */
    boolean hasVar1();
    /**
     * <code>required string var1 = 1;</code>
     */
    java.lang.String getVar1();
    /**
     * <code>required string var1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getVar1Bytes();
  }
  /**
   * Protobuf type {@code QueryString}
   */
  public  static final class QueryString extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QueryString)
      QueryStringOrBuilder {
    // Use QueryString.newBuilder() to construct.
    private QueryString(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryString() {
      var1_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryString(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              var1_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.auzmor.protobuf.QueryProtoBuf.internal_static_QueryString_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.auzmor.protobuf.QueryProtoBuf.internal_static_QueryString_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.auzmor.protobuf.QueryProtoBuf.QueryString.class, com.auzmor.protobuf.QueryProtoBuf.QueryString.Builder.class);
    }

    private int bitField0_;
    public static final int VAR1_FIELD_NUMBER = 1;
    private volatile java.lang.Object var1_;
    /**
     * <code>required string var1 = 1;</code>
     */
    public boolean hasVar1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string var1 = 1;</code>
     */
    public java.lang.String getVar1() {
      java.lang.Object ref = var1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          var1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string var1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVar1Bytes() {
      java.lang.Object ref = var1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        var1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVar1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, var1_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, var1_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.auzmor.protobuf.QueryProtoBuf.QueryString)) {
        return super.equals(obj);
      }
      com.auzmor.protobuf.QueryProtoBuf.QueryString other = (com.auzmor.protobuf.QueryProtoBuf.QueryString) obj;

      boolean result = true;
      result = result && (hasVar1() == other.hasVar1());
      if (hasVar1()) {
        result = result && getVar1()
            .equals(other.getVar1());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasVar1()) {
        hash = (37 * hash) + VAR1_FIELD_NUMBER;
        hash = (53 * hash) + getVar1().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.auzmor.protobuf.QueryProtoBuf.QueryString parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.auzmor.protobuf.QueryProtoBuf.QueryString parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.auzmor.protobuf.QueryProtoBuf.QueryString parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.auzmor.protobuf.QueryProtoBuf.QueryString parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.auzmor.protobuf.QueryProtoBuf.QueryString parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.auzmor.protobuf.QueryProtoBuf.QueryString parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.auzmor.protobuf.QueryProtoBuf.QueryString parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.auzmor.protobuf.QueryProtoBuf.QueryString parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.auzmor.protobuf.QueryProtoBuf.QueryString parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.auzmor.protobuf.QueryProtoBuf.QueryString parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.auzmor.protobuf.QueryProtoBuf.QueryString prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QueryString}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QueryString)
        com.auzmor.protobuf.QueryProtoBuf.QueryStringOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.auzmor.protobuf.QueryProtoBuf.internal_static_QueryString_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.auzmor.protobuf.QueryProtoBuf.internal_static_QueryString_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.auzmor.protobuf.QueryProtoBuf.QueryString.class, com.auzmor.protobuf.QueryProtoBuf.QueryString.Builder.class);
      }

      // Construct using com.auzmor.protobuf.QueryProtoBuf.QueryString.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        var1_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.auzmor.protobuf.QueryProtoBuf.internal_static_QueryString_descriptor;
      }

      public com.auzmor.protobuf.QueryProtoBuf.QueryString getDefaultInstanceForType() {
        return com.auzmor.protobuf.QueryProtoBuf.QueryString.getDefaultInstance();
      }

      public com.auzmor.protobuf.QueryProtoBuf.QueryString build() {
        com.auzmor.protobuf.QueryProtoBuf.QueryString result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.auzmor.protobuf.QueryProtoBuf.QueryString buildPartial() {
        com.auzmor.protobuf.QueryProtoBuf.QueryString result = new com.auzmor.protobuf.QueryProtoBuf.QueryString(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.var1_ = var1_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.auzmor.protobuf.QueryProtoBuf.QueryString) {
          return mergeFrom((com.auzmor.protobuf.QueryProtoBuf.QueryString)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.auzmor.protobuf.QueryProtoBuf.QueryString other) {
        if (other == com.auzmor.protobuf.QueryProtoBuf.QueryString.getDefaultInstance()) return this;
        if (other.hasVar1()) {
          bitField0_ |= 0x00000001;
          var1_ = other.var1_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVar1()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.auzmor.protobuf.QueryProtoBuf.QueryString parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.auzmor.protobuf.QueryProtoBuf.QueryString) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object var1_ = "";
      /**
       * <code>required string var1 = 1;</code>
       */
      public boolean hasVar1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string var1 = 1;</code>
       */
      public java.lang.String getVar1() {
        java.lang.Object ref = var1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            var1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string var1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVar1Bytes() {
        java.lang.Object ref = var1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          var1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string var1 = 1;</code>
       */
      public Builder setVar1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        var1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string var1 = 1;</code>
       */
      public Builder clearVar1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        var1_ = getDefaultInstance().getVar1();
        onChanged();
        return this;
      }
      /**
       * <code>required string var1 = 1;</code>
       */
      public Builder setVar1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        var1_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QueryString)
    }

    // @@protoc_insertion_point(class_scope:QueryString)
    private static final com.auzmor.protobuf.QueryProtoBuf.QueryString DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.auzmor.protobuf.QueryProtoBuf.QueryString();
    }

    public static com.auzmor.protobuf.QueryProtoBuf.QueryString getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<QueryString>
        PARSER = new com.google.protobuf.AbstractParser<QueryString>() {
      public QueryString parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new QueryString(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryString> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryString> getParserForType() {
      return PARSER;
    }

    public com.auzmor.protobuf.QueryProtoBuf.QueryString getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryString_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021querystring.proto\"\033\n\013QueryString\022\014\n\004va" +
      "r1\030\001 \002(\tB$\n\023com.auzmor.protobufB\rQueryPr" +
      "otoBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_QueryString_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QueryString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryString_descriptor,
        new java.lang.String[] { "Var1", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
